### ISSUE TITLE
Additional support for the SSML Standard

### ISSUE THREAD

**Issue by TTWNO** [pykeio/ssml#1]
I'm writing a crate for [Spiel](https://github.com/eeejay/spiel?tab=readme-ov-file), a new speech-synthesis API for Linux. As part of this, it specifies various features that may (or may not be) supported by each given voice, including very detailed SSML features as a bitflag.

I'd like to be able to use this `ssml` crate for the project such that it can embed SSML content within the request to speak text. For this though, I will need some additional types in the `ssml` crate.

For example, at first glance it's missing:

- [`Prosody`](https://www.w3.org/TR/speech-synthesis/#edef_prosody)
- [`SayAs`](https://www.w3.org/TR/speech-synthesis/#edef_say-as)

I'd be happy to contribute, as long as you are open to additional types being supported in the crate.

**Comment by TTWNO** [comment]
[List of SSML features potentially supposed by Spiel-attached engines](https://eeejay.github.io/spiel/flags.VoiceFeature.html)

**Comment by decahedron1** [comment]
A PR for `<prosody>` and `<say-as>` would be great! I'm going to be busy the next few days but if you could take care of those two I'll implement the rest of the elements as soon as I'm able.
