### ISSUE TITLE
User `serde` for Serialization (at least optionally)

### ISSUE THREAD

**Issue by TTWNO** [pykeio/ssml#2]
I'm all for squeezing the last bit of performance out of a module, but I'm curious if you'd be open to adding `serde` support for (de)serializing SSML? This will make the crate much more interoperable with other crates/ecosystems, and would have the added benefit of not requiring manual implementations.

I believe `serde` has the required flexibility to create SSML output with few issues.

As with #1, I'd be happy to contribute this, as long as you are open to the idea.

**Comment by decahedron1** [comment]
Great idea, but I'm not sure how this would work with dyn elements since `serde::Serialize` is not object safe.

**Comment by TTWNO** [comment]
You are right. You'd need to move to using generics instead of `dyn`s. This incurs binary bloat in exchange for a lack of a vtable lookup.
